export const spicesProducts = [
    { id: 1, title: "Cumin Seeds", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Cumin-Seeds-1.jpg" },
    { id: 2, title: "Coriander Seeds", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Coriander-Seeds-1.jpg" },
    { id: 3, title: "Fennel Seeds", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Fennel-Seed.jpg" },
    { id: 4, title: "Fenugreek Seeds", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Fenugreek-Seeds.jpg" },
    { id: 5, title: "Mustard Seeds", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Mustard-Seeds.jpg" },
    { id: 6, title: "Red Chilli", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Red-Chilli.jpg" },
    { id: 7, title: "Psyllium Seed", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Psyllium-Seed.jpg" },
    { id: 8, title: "Turmeric", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Turmeric.jpg" },
    { id: 9, title: "Red chilli Powder", image: "http://oesexportimport.com/wp-content/uploads/2021/01/red-chilli-powder.jpg" },
    { id: 10, title: "Turmeric Powder", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Turmeric-Powder.jpg" },
    { id: 11, title: "Black Pepper Powder", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Black-Pepper-Powder.jpg" },
    { id: 12, title: "Coriander seeds Powder", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Coriander-Seed-Powder.jpg" },
    { id: 13, title: "Garlic Powder", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Garlic-Powder.jpg" },
    { id: 14, title: "Dry Mango Powder", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Dry-Mango-Powder.jpg" },
    { id: 15, title: "Garam Masala", image: "https://oesexportimport.com/wp-content/uploads/2021/01/Garam-Masala-Powder.jpg" },
    { id: 16, title: "White Pepper Powder", image: "https://oesexportimport.com/wp-content/uploads/2020/12/White-Pepper-Powder.jpg" },
    { id: 17, title: "Nutmeg Powder", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Nutmeg-Powder.jpg" },
    { id: 18, title: "Dry Ginger Powder", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Dry-Ginger-Powder.jpg" },
    { id: 19, title: "Clove Powder", image: "https://oesexportimport.com/wp-content/uploads/2020/12/Clove-Powder.jpg" },
];