export const spicesProducts = [
    { id: 1, title: "Cumin Seeds", image: "/images/Cumin Seeds.jpeg" },
    { id: 2, title: "Coriander Seeds", image: "/images/Coriander Seeds.jpeg" },
    { id: 3, title: "Fennel Seeds", image: "/images/Fennel Seeds.jpeg" },
    { id: 4, title: "Fenugreek Seeds", image: "/images/Fenugreek Seeds.jpeg" },
    { id: 5, title: "Mustard Seeds", image: "/images/Mustard Seeds.jpeg" },
    { id: 6, title: "Red Chilli", image: "/images/Red Chilli Whole.jpeg" },
    { id: 7, title: "Psyllium Seed", image: "/images/Psyllium.jpeg" },
    { id: 8, title: "Turmeric", image: "/images/Turmeric Whole.jpeg" },
    { id: 9, title: "Red chilli Powder", image: "/images/Red chilli Powder.jpeg" },
    { id: 10, title: "Turmeric Powder", image: "/images/Turmeric.jpeg" },
    { id: 11, title: "Black Pepper Powder", image: "/images/Black Pepper.jpeg" },
    { id: 12, title: "Coriander seeds Powder", image: "/images/Coriander Seeds.jpeg" },
    { id: 13, title: "Garlic Powder", image: "/images/Garlic Powder.jpeg" },
    { id: 14, title: "Dry Mango Powder", image: "/images/Dry Mango Powder.jpeg" },
    { id: 15, title: "Garam Masala", image: "/images/Garam Masala.jpeg" },
    { id: 16, title: "White Pepper Powder", image: "/images/White Pepper.jpeg" },
    { id: 17, title: "Nutmeg Powder", image: "/images/Nut Meg.jpeg" },
    { id: 18, title: "Dry Ginger Powder", image: "/images/Dry Ginger.jpeg" },
    { id: 19, title: "Clove Powder", image: "/images/Clove.jpeg" },
];