export const gallery = [
    { id: 1, title: " ", image: "/images/Pizza.jpeg" },
    { id: 2, title: " ", image: "/images/Thepla.jpeg" },
    { id: 3, title: " ", image: "/images/Namkeen Mixture.jpeg" },
    { id: 4, title: " ", image: "/images/Soya Sticks.jpeg" },
    { id: 5, title: " ", image: "/images/Garam Masala.jpeg" },
    { id: 6, title: " ", image: "/images/Psyllium.jpeg" },
    { id: 7, title: " ", image: "/images/Turmeric.jpeg" },
    { id: 8, title: " ", image: "/images/Red Chilli Powder.jpeg" },
    { id: 9, title: " ", image: "/images/Green Gram Beans.jpeg" },
    { id: 10, title: "", image: "/images/Masoor Dal.jpeg" },
    { id: 11, title: " ", image: "/images/Toor Dal.jpeg" },
    { id: 12, title: " ", image: "/images/Urad Dal.jpeg" },
    { id: 13, title: " ", image: "/images/Non Basmati IR 64 Rice.jpeg" },
    { id: 14, title: " ", image: "/images/Basmati Rice 1718.jpeg" },
];