export const surgicalEquipmentProducts = [
    { id: 1, title: "Genral Instrument\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-1.jpg" },
    { id: 2, title: "Gynec Instrument\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-2.jpg" },
    { id: 3, title: "syringe With Needle\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-3.jpg" },
    { id: 4, title: "Urometer With Urine Bag\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-4.jpg" },
    { id: 5, title: "Suction Catheter\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-5.jpg" },
    { id: 6, title: "Syringe PUMP\n\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-6.png" },
    { id: 7, title: "Nasal Cannula\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-7.jpg" },
    { id: 8, title: "Oxygen Mask\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-8.jpg" },
    { id: 9, title: "Nebuliser Mask\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-9.jpg" },
    { id: 10, title: "Guedel Airway\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-10.jpg" },
    { id: 11, title: "ET Tube Plain\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-11.jpg" },
    { id: 12, title: "ET Tube Cuffed\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-12.jpg" },
    { id: 13, title: "Ryles Tube\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-13.jpg" },
    { id: 14, title: "Infant Feeding Tube\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-14.jpg" },
    { id: 15, title: "Mucus Extractor\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-15.jpg" },
    { id: 16, title: "Urine Bag\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-16.jpg" },
    { id: 17, title: "Folleys Catheter\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-17.jpg" },
    { id: 18, title: "Transfusion Infusion\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-18.jpg" },
    { id: 19, title: "IV Cannula\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-19.jpg" },
    { id: 20, title: "Extension Line\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-20.jpg" },
    { id: 21, title: "Scalp Vein\n", image: "https://www.aedmexlifecare.in/assets/images/img/s-product-21.jpg" },
];